#!/usr/bin/sh

activeHex="#fcda92"
innactiveHex="#bc7b76"
emptyHex="#695b72"


print_workspaces(){
  current=$(hyprctl activeworkspace -j | jq '.id')
  workspaces=$(hyprctl workspaces -j | jq ".[].id" | sed '/^ *-99 *$/d')
  res=""
  declare -a wsIco
  declare -a wsCls
  for wi in $(seq 1 10); do wsIco[$wi]=""; wsCls[$wi]="off"; done
  for ws in $(IFS='\n'; echo $workspaces); do wsIco[$ws]="󰊠"; wsCls[$ws]="innactive"; done
  wsIco[$current]="󰮯"
  wsCls[$current]="active"
  for w in $(seq 1 10); do
    res+="(box :class \"workspace\" (eventbox :onclick \"hyprctl dispatch workspace $w\" :class \"workspace-event\" (box :class \"workspace-inner\" (label :class \"workspace-ico ${wsCls[$w]}\" :text \"${wsIco[$w]}\"))))"
  done
  echo "(box :class \"workspaces\" (box :class \"workspaces-inner\" :orientation \"v\" :spacing 6 :space-evenly false $res))"
}


print_workspaces
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
  [[ $line == workspace* ]] && print_workspaces &
done
